-- Durable runtime evidence for the long-lived collection Worker.
-- The instance table is a current snapshot; this append-only sample table is
-- what lets operations prove a continuous heartbeat window after deployment.

BEGIN;

CREATE TABLE IF NOT EXISTS public.collection_worker_heartbeat_samples (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id TEXT NOT NULL,
  boot_id TEXT NOT NULL DEFAULT 'legacy',
  status TEXT NOT NULL CHECK (status IN ('starting', 'ready', 'busy', 'draining', 'stopped', 'error')),
  current_task_id UUID,
  observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  CHECK (char_length(worker_id) BETWEEN 1 AND 160),
  CHECK (char_length(boot_id) BETWEEN 1 AND 160),
  CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_collection_worker_heartbeat_samples_lookup
  ON public.collection_worker_heartbeat_samples(worker_id, observed_at DESC);

CREATE INDEX IF NOT EXISTS idx_collection_worker_heartbeat_samples_retention
  ON public.collection_worker_heartbeat_samples(observed_at);

CREATE OR REPLACE FUNCTION public.heartbeat_collection_worker(
  p_worker_id TEXT,
  p_status TEXT DEFAULT 'ready',
  p_deployment_id TEXT DEFAULT NULL,
  p_release_id TEXT DEFAULT NULL,
  p_current_task_id UUID DEFAULT NULL,
  p_metadata JSONB DEFAULT '{}'::jsonb
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  clean_worker_id TEXT := LEFT(NULLIF(TRIM(p_worker_id), ''), 160);
  clean_status TEXT := LOWER(COALESCE(NULLIF(TRIM(p_status), ''), 'ready'));
  clean_metadata JSONB := COALESCE(p_metadata, '{}'::jsonb);
  clean_boot_id TEXT;
  acknowledged_at TIMESTAMPTZ := NOW();
BEGIN
  IF clean_worker_id IS NULL THEN
    RAISE EXCEPTION 'WORKER_ID_REQUIRED' USING ERRCODE = '22023';
  END IF;
  IF clean_status NOT IN ('starting', 'ready', 'busy', 'draining', 'stopped', 'error') THEN
    RAISE EXCEPTION 'WORKER_STATUS_INVALID' USING ERRCODE = '22023';
  END IF;
  IF jsonb_typeof(clean_metadata) <> 'object' OR octet_length(clean_metadata::TEXT) > 4096 THEN
    RAISE EXCEPTION 'WORKER_METADATA_INVALID' USING ERRCODE = '22023';
  END IF;
  clean_boot_id := LEFT(NULLIF(TRIM(COALESCE(clean_metadata->>'boot_id', '')), ''), 160);
  IF clean_boot_id IS NULL THEN
    clean_boot_id := 'legacy';
  END IF;

  INSERT INTO public.collection_worker_instances(
    worker_id, deployment_id, release_id, status, current_task_id,
    started_at, last_seen_at, metadata, updated_at
  )
  VALUES (
    clean_worker_id, LEFT(NULLIF(TRIM(p_deployment_id), ''), 160),
    LEFT(NULLIF(TRIM(p_release_id), ''), 160), clean_status,
    p_current_task_id, acknowledged_at, acknowledged_at, clean_metadata, acknowledged_at
  )
  ON CONFLICT (worker_id) DO UPDATE SET
    deployment_id = COALESCE(EXCLUDED.deployment_id, collection_worker_instances.deployment_id),
    release_id = COALESCE(EXCLUDED.release_id, collection_worker_instances.release_id),
    status = EXCLUDED.status,
    current_task_id = EXCLUDED.current_task_id,
    last_seen_at = acknowledged_at,
    metadata = EXCLUDED.metadata,
    updated_at = acknowledged_at;

  INSERT INTO public.collection_worker_heartbeat_samples(
    worker_id, boot_id, status, current_task_id, observed_at, metadata
  ) VALUES (
    clean_worker_id, clean_boot_id, clean_status, p_current_task_id, acknowledged_at, clean_metadata
  );

  -- Keep the evidence table bounded without making the heartbeat path depend
  -- on a separate maintenance job. This is deliberately longer than the
  -- 24-hour acceptance window.
  DELETE FROM public.collection_worker_heartbeat_samples
   WHERE observed_at < acknowledged_at - INTERVAL '35 days';

  RETURN jsonb_build_object(
    'worker_id', clean_worker_id,
    'boot_id', clean_boot_id,
    'status', clean_status,
    'acknowledged_at', acknowledged_at
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.get_collection_worker_runtime_evidence(
  p_worker_id TEXT DEFAULT NULL,
  p_window_hours INTEGER DEFAULT 24
)
RETURNS JSONB
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  WITH bounds AS (
    SELECT NOW() AS checked_at,
           GREATEST(1, LEAST(COALESCE(p_window_hours, 24), 720))::INTEGER AS window_hours
  ),
  sample_rows AS (
    SELECT sample.observed_at, sample.status, sample.boot_id,
           LAG(sample.observed_at) OVER (ORDER BY sample.observed_at) AS previous_at
      FROM public.collection_worker_heartbeat_samples AS sample
      CROSS JOIN bounds
     WHERE (NULLIF(TRIM(p_worker_id), '') IS NULL OR sample.worker_id = LEFT(TRIM(p_worker_id), 160))
       AND sample.observed_at >= bounds.checked_at - make_interval(hours => bounds.window_hours)
  ),
  sample_stats AS (
    SELECT COUNT(*) AS heartbeat_count,
           MIN(observed_at) AS first_heartbeat_at,
           MAX(observed_at) AS last_heartbeat_at,
           COALESCE(MAX(EXTRACT(EPOCH FROM (observed_at - previous_at))), 0)::NUMERIC AS max_gap_seconds,
           COUNT(DISTINCT boot_id) AS boot_count
      FROM sample_rows
  ),
  attempt_rows AS (
    SELECT attempt.status, attempt.request_id, attempt.task_id, attempt.attempt_number
      FROM public.collection_task_attempts AS attempt
      CROSS JOIN bounds
     WHERE (NULLIF(TRIM(p_worker_id), '') IS NULL OR attempt.worker_id = LEFT(TRIM(p_worker_id), 160))
       AND attempt.started_at >= bounds.checked_at - make_interval(hours => bounds.window_hours)
  ),
  task_stats AS (
    SELECT COUNT(*) AS attempt_count,
           COUNT(DISTINCT request_id) AS distinct_request_count,
           COUNT(DISTINCT task_id::TEXT || ':' || attempt_number::TEXT) AS distinct_attempt_count,
           COALESCE((
             SELECT jsonb_object_agg(grouped.status, grouped.status_count)
               FROM (
                 SELECT status, COUNT(*) AS status_count
                   FROM attempt_rows
                  GROUP BY status
               ) grouped
           ), '{}'::jsonb) AS status_counts
      FROM attempt_rows
  ),
  queue_stats AS (
    SELECT COALESCE(jsonb_object_agg(status, status_count), '{}'::jsonb) AS status_counts
      FROM (
        SELECT task.status, COUNT(*) AS status_count
          FROM public.collection_tasks AS task
         WHERE task.updated_at >= NOW() - make_interval(hours => GREATEST(1, LEAST(COALESCE(p_window_hours, 24), 720)))
         GROUP BY task.status
      ) grouped_tasks
  )
  SELECT jsonb_build_object(
    'worker_id', NULLIF(TRIM(p_worker_id), ''),
    'window_hours', bounds.window_hours,
    'checked_at', bounds.checked_at,
    'heartbeat_count', sample_stats.heartbeat_count,
    'first_heartbeat_at', sample_stats.first_heartbeat_at,
    'last_heartbeat_at', sample_stats.last_heartbeat_at,
    'coverage_seconds', COALESCE(EXTRACT(EPOCH FROM (sample_stats.last_heartbeat_at - sample_stats.first_heartbeat_at)), 0)::NUMERIC,
    'max_gap_seconds', sample_stats.max_gap_seconds,
    'boot_count', sample_stats.boot_count,
    'attempt_count', task_stats.attempt_count,
    'distinct_request_count', task_stats.distinct_request_count,
    'duplicate_request_count', task_stats.attempt_count - task_stats.distinct_request_count,
    'distinct_attempt_count', task_stats.distinct_attempt_count,
    'duplicate_attempt_count', task_stats.attempt_count - task_stats.distinct_attempt_count,
    'attempt_status_counts', task_stats.status_counts,
    'task_status_counts', queue_stats.status_counts
  )
    FROM bounds, sample_stats, task_stats, queue_stats;
$$;

ALTER TABLE public.collection_worker_heartbeat_samples ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.collection_worker_heartbeat_samples FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.collection_worker_heartbeat_samples TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.collection_worker_heartbeat_samples_id_seq TO service_role;

REVOKE ALL ON FUNCTION public.get_collection_worker_runtime_evidence(TEXT, INTEGER)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_collection_worker_runtime_evidence(TEXT, INTEGER)
  TO service_role;

COMMENT ON TABLE public.collection_worker_heartbeat_samples IS
  'Append-only service evidence for proving Worker heartbeat continuity and boot sessions.';
COMMENT ON FUNCTION public.get_collection_worker_runtime_evidence(TEXT, INTEGER) IS
  'Returns heartbeat continuity, task-attempt uniqueness and queue status for an operations window.';

COMMIT;
