-- R10: durable Worker fencing, circuit probes, logical budget idempotency and audit evidence.
-- The v2 RPCs coexist with the original protocol so the database can be deployed
-- before the long-lived Worker image. The scheduler only cuts over after it sees
-- three recent protocol-v2 heartbeats.

BEGIN;

ALTER TABLE public.collection_tasks
  ADD COLUMN IF NOT EXISTS lease_token UUID,
  ADD COLUMN IF NOT EXISTS lease_boot_id TEXT,
  ADD COLUMN IF NOT EXISTS budget_request_id TEXT;

ALTER TABLE public.collection_task_attempts
  ADD COLUMN IF NOT EXISTS lease_token UUID,
  ADD COLUMN IF NOT EXISTS budget_request_id TEXT;

ALTER TABLE public.collection_source_policies
  ADD COLUMN IF NOT EXISTS circuit_probe_task_id UUID,
  ADD COLUMN IF NOT EXISTS circuit_probe_lease_token UUID,
  ADD COLUMN IF NOT EXISTS circuit_half_opened_at TIMESTAMPTZ;

ALTER TABLE public.collection_tasks
  DROP CONSTRAINT IF EXISTS collection_tasks_status_check;
ALTER TABLE public.collection_tasks
  ADD CONSTRAINT collection_tasks_status_check
  CHECK (status IN ('queued', 'leased', 'retry_wait', 'succeeded', 'dead_letter', 'budget_blocked', 'cancelled'));

CREATE TABLE IF NOT EXISTS public.collection_source_outcomes (
  lease_token UUID PRIMARY KEY,
  task_id UUID NOT NULL REFERENCES public.collection_tasks(id) ON DELETE CASCADE,
  source_key TEXT NOT NULL REFERENCES public.data_source_registry(source_key) ON DELETE RESTRICT,
  success BOOLEAN NOT NULL,
  error_code TEXT,
  circuit_state_after TEXT NOT NULL CHECK (circuit_state_after IN ('closed', 'open', 'half_open')),
  consecutive_failures_after INTEGER NOT NULL CHECK (consecutive_failures_after >= 0),
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.collection_worker_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL CHECK (event_type IN (
    'task_claimed', 'lease_expired', 'lease_renew_rejected',
    'attempt_write_rejected', 'completion_rejected', 'failure_rejected',
    'task_completed', 'task_failed', 'budget_blocked',
    'circuit_opened', 'circuit_half_opened', 'circuit_closed'
  )),
  task_id UUID REFERENCES public.collection_tasks(id) ON DELETE CASCADE,
  source_key TEXT REFERENCES public.data_source_registry(source_key) ON DELETE RESTRICT,
  worker_id TEXT,
  boot_id TEXT,
  lease_token UUID,
  idempotency_key TEXT UNIQUE,
  detail JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (jsonb_typeof(detail) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_collection_worker_events_created
  ON public.collection_worker_events(created_at DESC, event_type);
CREATE INDEX IF NOT EXISTS idx_collection_source_outcomes_task
  ON public.collection_source_outcomes(task_id, recorded_at DESC);

-- Once an R10 Worker announces itself, protocol-v1 instances stop taking new
-- work. They may still finish a pre-existing, unfenced lease.
CREATE OR REPLACE FUNCTION public.claim_collection_task(
  p_worker_id TEXT,
  p_lease_seconds INTEGER DEFAULT 900
)
RETURNS SETOF public.collection_tasks
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE lease_seconds INTEGER := GREATEST(30, LEAST(COALESCE(p_lease_seconds, 900), 86400));
BEGIN
  IF NULLIF(TRIM(p_worker_id), '') IS NULL THEN
    RAISE EXCEPTION 'WORKER_ID_REQUIRED' USING ERRCODE = '22023';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.collection_worker_instances
     WHERE status IN ('starting', 'ready', 'busy')
       AND last_seen_at >= NOW() - INTERVAL '2 minutes'
       AND metadata->>'protocol_version' = '2'
  ) THEN
    RETURN;
  END IF;

  PERFORM pg_advisory_xact_lock(hashtextextended('collection-task-claim', 0));
  UPDATE public.collection_tasks
     SET status = 'queued', lease_owner = NULL, lease_expires_at = NULL,
         last_heartbeat_at = NULL, run_after = NOW(), updated_at = NOW()
   WHERE status = 'leased' AND lease_token IS NULL
     AND lease_expires_at IS NOT NULL AND lease_expires_at <= NOW();

  RETURN QUERY
  WITH candidate AS (
    SELECT task.id
      FROM public.collection_tasks AS task
      JOIN public.collection_source_policies AS policy USING (source_key)
     WHERE task.status IN ('queued', 'retry_wait')
       AND task.run_after <= NOW()
       AND policy.enabled = TRUE
       AND NOT EXISTS (
         SELECT 1
           FROM unnest(task.depends_on_task_keys) AS dependency_key
           LEFT JOIN public.collection_tasks AS dependency ON dependency.task_key = dependency_key
          WHERE dependency.id IS NULL OR dependency.status <> 'succeeded'
       )
       AND policy.circuit_state = 'closed'
       AND (
         SELECT COUNT(*) FROM public.collection_tasks AS active
          WHERE active.source_key = task.source_key
            AND active.status = 'leased' AND active.lease_expires_at > NOW()
       ) < policy.max_concurrency
     ORDER BY task.priority DESC, task.run_after, task.created_at
     FOR UPDATE OF task SKIP LOCKED
     LIMIT 1
  )
  UPDATE public.collection_tasks AS task
     SET status = 'leased', lease_owner = LEFT(TRIM(p_worker_id), 160),
         lease_expires_at = NOW() + make_interval(secs => lease_seconds),
         last_heartbeat_at = NOW(), last_started_at = NOW(),
         attempt_count = task.attempt_count + 1, updated_at = NOW()
    FROM candidate
   WHERE task.id = candidate.id
  RETURNING task.*;
END;
$$;

-- Protocol-v1 finalization is limited to leases created before fencing existed.
CREATE OR REPLACE FUNCTION public.renew_collection_task_lease(
  p_task_id UUID, p_worker_id TEXT, p_lease_seconds INTEGER DEFAULT 900
)
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  UPDATE public.collection_tasks
     SET lease_expires_at = NOW() + make_interval(secs => GREATEST(30, LEAST(COALESCE(p_lease_seconds, 900), 86400))),
         last_heartbeat_at = NOW(), updated_at = NOW()
   WHERE id = p_task_id AND status = 'leased' AND lease_token IS NULL
     AND lease_owner = LEFT(TRIM(p_worker_id), 160) AND lease_expires_at > NOW()
  RETURNING TRUE;
$$;

CREATE OR REPLACE FUNCTION public.complete_collection_task(
  p_task_id UUID, p_worker_id TEXT, p_result_summary JSONB DEFAULT '{}'::jsonb
)
RETURNS public.collection_tasks
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE result_row public.collection_tasks;
BEGIN
  UPDATE public.collection_tasks
     SET status = 'succeeded', lease_owner = NULL, lease_expires_at = NULL,
         last_heartbeat_at = NULL, last_finished_at = NOW(),
         result_summary = COALESCE(p_result_summary, '{}'::jsonb),
         last_error_code = NULL, last_error = NULL, updated_at = NOW()
   WHERE id = p_task_id AND status = 'leased' AND lease_token IS NULL
     AND lease_owner = LEFT(TRIM(p_worker_id), 160) AND lease_expires_at > NOW()
  RETURNING * INTO result_row;
  IF NOT FOUND THEN RAISE EXCEPTION 'TASK_LEASE_NOT_OWNED' USING ERRCODE = '42501'; END IF;
  RETURN result_row;
END;
$$;

CREATE OR REPLACE FUNCTION public.fail_collection_task(
  p_task_id UUID, p_worker_id TEXT, p_error_code TEXT, p_error_message TEXT,
  p_backoff_seconds INTEGER DEFAULT 60, p_retryable BOOLEAN DEFAULT TRUE
)
RETURNS public.collection_tasks
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE result_row public.collection_tasks;
BEGIN
  UPDATE public.collection_tasks
     SET status = CASE WHEN p_retryable AND attempt_count < max_attempts THEN 'retry_wait' ELSE 'dead_letter' END,
         lease_owner = NULL, lease_expires_at = NULL, last_heartbeat_at = NULL,
         last_finished_at = NOW(), next_attempt_at = CASE
           WHEN p_retryable AND attempt_count < max_attempts
           THEN NOW() + make_interval(secs => GREATEST(1, LEAST(COALESCE(p_backoff_seconds, 60), 604800)))
           ELSE NULL END,
         run_after = CASE WHEN p_retryable AND attempt_count < max_attempts
           THEN NOW() + make_interval(secs => GREATEST(1, LEAST(COALESCE(p_backoff_seconds, 60), 604800)))
           ELSE NOW() END,
         last_error_code = LEFT(NULLIF(TRIM(p_error_code), ''), 120),
         last_error = LEFT(NULLIF(TRIM(p_error_message), ''), 2000), updated_at = NOW()
   WHERE id = p_task_id AND status = 'leased' AND lease_token IS NULL
     AND lease_owner = LEFT(TRIM(p_worker_id), 160) AND lease_expires_at > NOW()
  RETURNING * INTO result_row;
  IF NOT FOUND THEN RAISE EXCEPTION 'TASK_LEASE_NOT_OWNED' USING ERRCODE = '42501'; END IF;
  RETURN result_row;
END;
$$;

CREATE OR REPLACE FUNCTION public.claim_collection_task_v2(
  p_worker_id TEXT,
  p_boot_id TEXT,
  p_lease_seconds INTEGER DEFAULT 900
)
RETURNS SETOF public.collection_tasks
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  lease_seconds INTEGER := GREATEST(30, LEAST(COALESCE(p_lease_seconds, 900), 86400));
  clean_worker_id TEXT := LEFT(NULLIF(TRIM(p_worker_id), ''), 160);
  clean_boot_id TEXT := LEFT(NULLIF(TRIM(p_boot_id), ''), 160);
  candidate_id UUID;
  candidate_source TEXT;
  previous_circuit_state TEXT;
  new_lease_token UUID := gen_random_uuid();
BEGIN
  IF clean_worker_id IS NULL OR clean_boot_id IS NULL THEN
    RAISE EXCEPTION 'WORKER_AND_BOOT_ID_REQUIRED' USING ERRCODE = '22023';
  END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended('collection-task-claim', 0));

  INSERT INTO public.collection_worker_events(
    event_type, task_id, source_key, worker_id, boot_id, lease_token, idempotency_key, detail
  )
  SELECT 'lease_expired', task.id, task.source_key, task.lease_owner, task.lease_boot_id,
         task.lease_token, 'lease-expired:' || task.id::TEXT || ':' || task.lease_token::TEXT,
         jsonb_build_object('attempt_number', task.attempt_count)
    FROM public.collection_tasks AS task
   WHERE task.status = 'leased' AND task.lease_token IS NOT NULL
     AND task.lease_expires_at IS NOT NULL AND task.lease_expires_at <= NOW()
  ON CONFLICT (idempotency_key) DO NOTHING;

  UPDATE public.collection_source_policies AS policy
     SET circuit_state = 'open',
         circuit_opened_at = NOW(),
         circuit_probe_task_id = NULL, circuit_probe_lease_token = NULL,
         circuit_half_opened_at = NULL, updated_at = NOW()
    FROM public.collection_tasks AS task
   WHERE task.status = 'leased' AND task.lease_expires_at <= NOW()
     AND task.id = policy.circuit_probe_task_id
     AND task.lease_token = policy.circuit_probe_lease_token;

  UPDATE public.collection_tasks
     SET status = 'queued', lease_owner = NULL, lease_boot_id = NULL,
         lease_token = NULL, lease_expires_at = NULL, last_heartbeat_at = NULL,
         run_after = NOW(), updated_at = NOW()
   WHERE status = 'leased' AND lease_expires_at IS NOT NULL AND lease_expires_at <= NOW();

  SELECT task.id, task.source_key, policy.circuit_state
    INTO candidate_id, candidate_source, previous_circuit_state
    FROM public.collection_tasks AS task
    JOIN public.collection_source_policies AS policy USING (source_key)
   WHERE task.status IN ('queued', 'retry_wait')
     AND task.run_after <= NOW()
     AND policy.enabled = TRUE
     AND NOT EXISTS (
       SELECT 1
         FROM unnest(task.depends_on_task_keys) AS dependency_key
         LEFT JOIN public.collection_tasks AS dependency ON dependency.task_key = dependency_key
        WHERE dependency.id IS NULL OR dependency.status <> 'succeeded'
     )
     AND (
       policy.circuit_state = 'closed'
       OR (
         policy.circuit_state = 'open'
         AND policy.circuit_opened_at IS NOT NULL
         AND policy.circuit_opened_at + make_interval(secs => policy.circuit_cooldown_seconds) <= NOW()
       )
     )
     AND (
       SELECT COUNT(*) FROM public.collection_tasks AS active
        WHERE active.source_key = task.source_key
          AND active.status = 'leased' AND active.lease_expires_at > NOW()
     ) < policy.max_concurrency
   ORDER BY task.priority DESC, task.run_after, task.created_at
   FOR UPDATE OF task, policy SKIP LOCKED
   LIMIT 1;

  IF candidate_id IS NULL THEN
    RETURN;
  END IF;

  UPDATE public.collection_tasks AS task
     SET status = 'leased', lease_owner = clean_worker_id, lease_boot_id = clean_boot_id,
         lease_token = new_lease_token,
         budget_request_id = COALESCE(
           task.budget_request_id,
           'collection-budget:' || task.id::TEXT || ':' || (task.attempt_count + 1)::TEXT
         ),
         lease_expires_at = NOW() + make_interval(secs => lease_seconds),
         last_heartbeat_at = NOW(), last_started_at = NOW(),
         attempt_count = task.attempt_count + 1, updated_at = NOW()
   WHERE task.id = candidate_id;

  IF previous_circuit_state = 'open' THEN
    UPDATE public.collection_source_policies
       SET circuit_state = 'half_open', circuit_probe_task_id = candidate_id,
           circuit_probe_lease_token = new_lease_token, circuit_half_opened_at = NOW(), updated_at = NOW()
     WHERE source_key = candidate_source;
    INSERT INTO public.collection_worker_events(
      event_type, task_id, source_key, worker_id, boot_id, lease_token, idempotency_key
    ) VALUES (
      'circuit_half_opened', candidate_id, candidate_source, clean_worker_id, clean_boot_id,
      new_lease_token, 'circuit-half-opened:' || new_lease_token::TEXT
    ) ON CONFLICT (idempotency_key) DO NOTHING;
  END IF;

  INSERT INTO public.collection_worker_events(
    event_type, task_id, source_key, worker_id, boot_id, lease_token, idempotency_key
  ) VALUES (
    'task_claimed', candidate_id, candidate_source, clean_worker_id, clean_boot_id,
    new_lease_token, 'task-claimed:' || new_lease_token::TEXT
  ) ON CONFLICT (idempotency_key) DO NOTHING;

  RETURN QUERY SELECT task.* FROM public.collection_tasks AS task WHERE task.id = candidate_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.renew_collection_task_lease_v2(
  p_task_id UUID, p_worker_id TEXT, p_boot_id TEXT, p_lease_token UUID,
  p_lease_seconds INTEGER DEFAULT 900
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE renewed BOOLEAN;
BEGIN
  UPDATE public.collection_tasks
     SET lease_expires_at = NOW() + make_interval(secs => GREATEST(30, LEAST(COALESCE(p_lease_seconds, 900), 86400))),
         last_heartbeat_at = NOW(), updated_at = NOW()
   WHERE id = p_task_id AND status = 'leased'
     AND lease_owner = LEFT(TRIM(p_worker_id), 160)
     AND lease_boot_id = LEFT(TRIM(p_boot_id), 160)
     AND lease_token = p_lease_token AND lease_expires_at > NOW()
  RETURNING TRUE INTO renewed;
  IF COALESCE(renewed, FALSE) = FALSE THEN
    INSERT INTO public.collection_worker_events(
      event_type, task_id, worker_id, boot_id, lease_token, idempotency_key
    ) VALUES (
      'lease_renew_rejected', p_task_id, LEFT(TRIM(p_worker_id), 160), LEFT(TRIM(p_boot_id), 160),
      p_lease_token, 'lease-renew-rejected:' || p_lease_token::TEXT
    ) ON CONFLICT (idempotency_key) DO NOTHING;
  END IF;
  RETURN COALESCE(renewed, FALSE);
END;
$$;

CREATE OR REPLACE FUNCTION public.record_collection_task_attempt_v2(
  p_task_id UUID, p_worker_id TEXT, p_boot_id TEXT, p_lease_token UUID,
  p_attempt JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  owned BOOLEAN;
  inserted_id UUID;
  attempt_number INTEGER;
  clean_request_id TEXT;
  attempt_status TEXT;
BEGIN
  SELECT TRUE INTO owned FROM public.collection_tasks
   WHERE id = p_task_id AND status = 'leased'
     AND lease_owner = LEFT(TRIM(p_worker_id), 160)
     AND lease_boot_id = LEFT(TRIM(p_boot_id), 160)
     AND lease_token = p_lease_token AND lease_expires_at > NOW()
   FOR UPDATE;
  IF COALESCE(owned, FALSE) = FALSE THEN
    INSERT INTO public.collection_worker_events(
      event_type, task_id, worker_id, boot_id, lease_token, idempotency_key
    ) VALUES (
      'attempt_write_rejected', p_task_id, LEFT(TRIM(p_worker_id), 160), LEFT(TRIM(p_boot_id), 160),
      p_lease_token, 'attempt-write-rejected:' || p_lease_token::TEXT
    ) ON CONFLICT (idempotency_key) DO NOTHING;
    RETURN jsonb_build_object('recorded', FALSE, 'reason', 'LEASE_FENCED');
  END IF;

  attempt_number := GREATEST(1, COALESCE((p_attempt->>'attempt_number')::INTEGER, 1));
  clean_request_id := LEFT(NULLIF(TRIM(p_attempt->>'request_id'), ''), 240);
  attempt_status := NULLIF(TRIM(p_attempt->>'status'), '');
  IF clean_request_id IS NULL OR attempt_status NOT IN ('succeeded', 'failed', 'budget_blocked', 'source_blocked', 'timed_out') THEN
    RAISE EXCEPTION 'ATTEMPT_PAYLOAD_INVALID' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.collection_task_attempts(
    task_id, attempt_number, worker_id, request_id, status, exit_code,
    error_code, error_message, estimated_cost_usd, started_at, completed_at,
    diagnostics, lease_token, budget_request_id
  ) VALUES (
    p_task_id, attempt_number, LEFT(TRIM(p_worker_id), 160), clean_request_id, attempt_status,
    NULLIF(p_attempt->>'exit_code', '')::INTEGER,
    LEFT(NULLIF(TRIM(p_attempt->>'error_code'), ''), 120),
    LEFT(NULLIF(TRIM(p_attempt->>'error_message'), ''), 2000),
    GREATEST(0, COALESCE(NULLIF(p_attempt->>'estimated_cost_usd', '')::NUMERIC, 0)),
    COALESCE(NULLIF(p_attempt->>'started_at', '')::TIMESTAMPTZ, NOW()),
    COALESCE(NULLIF(p_attempt->>'completed_at', '')::TIMESTAMPTZ, NOW()),
    CASE WHEN jsonb_typeof(p_attempt->'diagnostics') = 'object' THEN p_attempt->'diagnostics' ELSE '{}'::jsonb END,
    p_lease_token, LEFT(NULLIF(TRIM(p_attempt->>'budget_request_id'), ''), 240)
  )
  ON CONFLICT ON CONSTRAINT collection_task_attempts_request_id_key DO NOTHING
  RETURNING id INTO inserted_id;

  RETURN jsonb_build_object('recorded', TRUE, 'idempotent', inserted_id IS NULL, 'request_id', clean_request_id);
END;
$$;

CREATE OR REPLACE FUNCTION public.record_collection_source_outcome_v2(
  p_task_id UUID, p_worker_id TEXT, p_boot_id TEXT, p_lease_token UUID,
  p_source_key TEXT, p_success BOOLEAN, p_error_code TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  owned BOOLEAN;
  policy public.collection_source_policies%ROWTYPE;
  existing public.collection_source_outcomes%ROWTYPE;
  failures INTEGER;
  result JSONB;
  event_name TEXT;
BEGIN
  PERFORM pg_advisory_xact_lock(
    hashtextextended('collection-source-outcome:' || p_lease_token::TEXT, 0)
  );
  SELECT * INTO existing FROM public.collection_source_outcomes WHERE lease_token = p_lease_token;
  IF FOUND THEN
    RETURN jsonb_build_object(
      'source_key', existing.source_key, 'success', existing.success,
      'circuit_state', existing.circuit_state_after,
      'consecutive_failures', existing.consecutive_failures_after,
      'error_code', existing.error_code, 'idempotent', TRUE
    );
  END IF;

  SELECT TRUE INTO owned FROM public.collection_tasks
   WHERE id = p_task_id AND source_key = p_source_key AND status = 'leased'
     AND lease_owner = LEFT(TRIM(p_worker_id), 160)
     AND lease_boot_id = LEFT(TRIM(p_boot_id), 160)
     AND lease_token = p_lease_token AND lease_expires_at > NOW()
   FOR UPDATE;
  IF COALESCE(owned, FALSE) = FALSE THEN
    RETURN jsonb_build_object('recorded', FALSE, 'reason', 'LEASE_FENCED');
  END IF;

  SELECT * INTO policy FROM public.collection_source_policies
   WHERE source_key = p_source_key FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'SOURCE_POLICY_NOT_FOUND' USING ERRCODE = '22023'; END IF;

  IF p_success THEN
    IF policy.circuit_state = 'closed'
       OR (policy.circuit_state = 'half_open'
           AND policy.circuit_probe_task_id = p_task_id
           AND policy.circuit_probe_lease_token = p_lease_token) THEN
      event_name := CASE WHEN policy.circuit_state = 'half_open' THEN 'circuit_closed' ELSE NULL END;
      UPDATE public.collection_source_policies
         SET circuit_state = 'closed', circuit_opened_at = NULL, last_failure_at = NULL,
             consecutive_failures = 0, circuit_probe_task_id = NULL,
             circuit_probe_lease_token = NULL, circuit_half_opened_at = NULL, updated_at = NOW()
       WHERE source_key = p_source_key;
    END IF;
  ELSIF policy.circuit_state = 'half_open'
        AND policy.circuit_probe_task_id = p_task_id
        AND policy.circuit_probe_lease_token = p_lease_token THEN
    event_name := 'circuit_opened';
    UPDATE public.collection_source_policies
       SET circuit_state = 'open', circuit_opened_at = NOW(), last_failure_at = NOW(),
           consecutive_failures = GREATEST(1, policy.consecutive_failures + 1),
           circuit_probe_task_id = NULL, circuit_probe_lease_token = NULL,
           circuit_half_opened_at = NULL, updated_at = NOW()
     WHERE source_key = p_source_key;
  ELSIF policy.circuit_state = 'closed' THEN
    failures := CASE
      WHEN policy.last_failure_at IS NULL
        OR policy.last_failure_at + make_interval(secs => policy.circuit_window_seconds) <= NOW()
      THEN 1 ELSE policy.consecutive_failures + 1 END;
    event_name := CASE WHEN failures >= policy.circuit_failure_threshold THEN 'circuit_opened' ELSE NULL END;
    UPDATE public.collection_source_policies
       SET consecutive_failures = failures, last_failure_at = NOW(),
           circuit_state = CASE WHEN failures >= circuit_failure_threshold THEN 'open' ELSE 'closed' END,
           circuit_opened_at = CASE WHEN failures >= circuit_failure_threshold THEN NOW() ELSE circuit_opened_at END,
           updated_at = NOW()
     WHERE source_key = p_source_key;
  END IF;

  SELECT * INTO policy FROM public.collection_source_policies WHERE source_key = p_source_key;
  INSERT INTO public.collection_source_outcomes(
    lease_token, task_id, source_key, success, error_code,
    circuit_state_after, consecutive_failures_after
  ) VALUES (
    p_lease_token, p_task_id, p_source_key, p_success,
    LEFT(NULLIF(TRIM(p_error_code), ''), 120), policy.circuit_state, policy.consecutive_failures
  );
  IF event_name IS NOT NULL THEN
    INSERT INTO public.collection_worker_events(
      event_type, task_id, source_key, worker_id, boot_id, lease_token, idempotency_key,
      detail
    ) VALUES (
      event_name, p_task_id, p_source_key, LEFT(TRIM(p_worker_id), 160), LEFT(TRIM(p_boot_id), 160),
      p_lease_token, event_name || ':' || p_lease_token::TEXT,
      jsonb_build_object('consecutive_failures', policy.consecutive_failures, 'error_code', p_error_code)
    ) ON CONFLICT (idempotency_key) DO NOTHING;
  END IF;
  result := jsonb_build_object(
    'source_key', policy.source_key, 'success', p_success,
    'circuit_state', policy.circuit_state,
    'consecutive_failures', policy.consecutive_failures,
    'blocks_publication_on_failure', policy.blocks_publication_on_failure,
    'error_code', p_error_code, 'idempotent', FALSE
  );
  RETURN result;
END;
$$;

CREATE OR REPLACE FUNCTION public.complete_collection_task_v2(
  p_task_id UUID, p_worker_id TEXT, p_boot_id TEXT, p_lease_token UUID,
  p_result_summary JSONB DEFAULT '{}'::jsonb
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE result_row public.collection_tasks%ROWTYPE;
BEGIN
  UPDATE public.collection_tasks
     SET status = 'succeeded', lease_owner = NULL, lease_boot_id = NULL,
         lease_token = NULL, lease_expires_at = NULL, last_heartbeat_at = NULL,
         last_finished_at = NOW(), result_summary = COALESCE(p_result_summary, '{}'::jsonb),
         last_error_code = NULL, last_error = NULL, updated_at = NOW()
   WHERE id = p_task_id AND status = 'leased'
     AND lease_owner = LEFT(TRIM(p_worker_id), 160)
     AND lease_boot_id = LEFT(TRIM(p_boot_id), 160)
     AND lease_token = p_lease_token AND lease_expires_at > NOW()
     AND EXISTS (
       SELECT 1 FROM public.collection_task_attempts
        WHERE task_id = p_task_id AND status = 'succeeded'
     )
  RETURNING * INTO result_row;
  IF NOT FOUND THEN
    INSERT INTO public.collection_worker_events(
      event_type, task_id, worker_id, boot_id, lease_token, idempotency_key
    ) VALUES (
      'completion_rejected', p_task_id, LEFT(TRIM(p_worker_id), 160), LEFT(TRIM(p_boot_id), 160),
      p_lease_token, 'completion-rejected:' || p_lease_token::TEXT
    ) ON CONFLICT (idempotency_key) DO NOTHING;
    RETURN jsonb_build_object('applied', FALSE, 'reason', 'LEASE_FENCED_OR_SUCCESS_NOT_RECORDED');
  END IF;
  INSERT INTO public.collection_worker_events(
    event_type, task_id, source_key, worker_id, boot_id, lease_token, idempotency_key
  ) VALUES (
    'task_completed', result_row.id, result_row.source_key, LEFT(TRIM(p_worker_id), 160),
    LEFT(TRIM(p_boot_id), 160), p_lease_token, 'task-completed:' || p_lease_token::TEXT
  ) ON CONFLICT (idempotency_key) DO NOTHING;
  RETURN jsonb_build_object('applied', TRUE, 'status', 'succeeded', 'task_id', result_row.id);
END;
$$;

CREATE OR REPLACE FUNCTION public.fail_collection_task_v2(
  p_task_id UUID, p_worker_id TEXT, p_boot_id TEXT, p_lease_token UUID,
  p_error_code TEXT, p_error_message TEXT,
  p_backoff_seconds INTEGER DEFAULT 60, p_retryable BOOLEAN DEFAULT TRUE
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  result_row public.collection_tasks%ROWTYPE;
  final_status TEXT;
BEGIN
  UPDATE public.collection_tasks
     SET status = CASE
           WHEN UPPER(COALESCE(p_error_code, '')) IN ('DAILY_REQUEST_LIMIT', 'DAILY_COST_LIMIT') THEN 'budget_blocked'
           WHEN p_retryable AND attempt_count < max_attempts THEN 'retry_wait'
           ELSE 'dead_letter' END,
         lease_owner = NULL, lease_boot_id = NULL, lease_token = NULL,
         lease_expires_at = NULL, last_heartbeat_at = NULL, last_finished_at = NOW(),
         next_attempt_at = CASE WHEN p_retryable AND attempt_count < max_attempts
           THEN NOW() + make_interval(secs => GREATEST(1, LEAST(COALESCE(p_backoff_seconds, 60), 604800)))
           ELSE NULL END,
         run_after = CASE WHEN p_retryable AND attempt_count < max_attempts
           THEN NOW() + make_interval(secs => GREATEST(1, LEAST(COALESCE(p_backoff_seconds, 60), 604800)))
           ELSE NOW() END,
         last_error_code = LEFT(NULLIF(TRIM(p_error_code), ''), 120),
         last_error = LEFT(NULLIF(TRIM(p_error_message), ''), 2000), updated_at = NOW()
   WHERE id = p_task_id AND status = 'leased'
     AND lease_owner = LEFT(TRIM(p_worker_id), 160)
     AND lease_boot_id = LEFT(TRIM(p_boot_id), 160)
     AND lease_token = p_lease_token AND lease_expires_at > NOW()
  RETURNING * INTO result_row;
  IF NOT FOUND THEN
    INSERT INTO public.collection_worker_events(
      event_type, task_id, worker_id, boot_id, lease_token, idempotency_key
    ) VALUES (
      'failure_rejected', p_task_id, LEFT(TRIM(p_worker_id), 160), LEFT(TRIM(p_boot_id), 160),
      p_lease_token, 'failure-rejected:' || p_lease_token::TEXT
    ) ON CONFLICT (idempotency_key) DO NOTHING;
    RETURN jsonb_build_object('applied', FALSE, 'reason', 'LEASE_FENCED');
  END IF;

  final_status := result_row.status;
  IF final_status IN ('budget_blocked', 'dead_letter') THEN
    UPDATE public.collection_source_policies
       SET circuit_state = CASE WHEN circuit_probe_task_id = p_task_id THEN 'open' ELSE circuit_state END,
           circuit_opened_at = CASE WHEN circuit_probe_task_id = p_task_id THEN NOW() ELSE circuit_opened_at END,
           circuit_probe_task_id = CASE WHEN circuit_probe_task_id = p_task_id THEN NULL ELSE circuit_probe_task_id END,
           circuit_probe_lease_token = CASE WHEN circuit_probe_task_id = p_task_id THEN NULL ELSE circuit_probe_lease_token END,
           circuit_half_opened_at = CASE WHEN circuit_probe_task_id = p_task_id THEN NULL ELSE circuit_half_opened_at END,
           updated_at = NOW()
     WHERE source_key = result_row.source_key;
  END IF;

  INSERT INTO public.collection_worker_events(
    event_type, task_id, source_key, worker_id, boot_id, lease_token, idempotency_key, detail
  ) VALUES (
    CASE WHEN final_status = 'budget_blocked' THEN 'budget_blocked' ELSE 'task_failed' END,
    result_row.id, result_row.source_key, LEFT(TRIM(p_worker_id), 160), LEFT(TRIM(p_boot_id), 160),
    p_lease_token, 'task-failed:' || p_lease_token::TEXT,
    jsonb_build_object('status', final_status, 'error_code', p_error_code, 'retryable', p_retryable)
  ) ON CONFLICT (idempotency_key) DO NOTHING;
  RETURN jsonb_build_object('applied', TRUE, 'status', final_status, 'task_id', result_row.id);
END;
$$;

CREATE OR REPLACE FUNCTION public.finalize_collection_task_v2(
  p_task_id UUID, p_worker_id TEXT, p_boot_id TEXT, p_lease_token UUID,
  p_attempt JSONB, p_source_key TEXT,
  p_record_source_outcome BOOLEAN, p_source_success BOOLEAN,
  p_source_error_code TEXT, p_result_summary JSONB,
  p_complete BOOLEAN, p_backoff_seconds INTEGER DEFAULT 60,
  p_retryable BOOLEAN DEFAULT TRUE
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  owned BOOLEAN;
  attempt_result JSONB;
  source_result JSONB := '{}'::jsonb;
  task_result JSONB;
BEGIN
  PERFORM pg_advisory_xact_lock(
    hashtextextended('collection-finalize:' || p_lease_token::TEXT, 0)
  );
  SELECT TRUE INTO owned FROM public.collection_tasks
   WHERE id = p_task_id AND source_key = p_source_key AND status = 'leased'
     AND lease_owner = LEFT(TRIM(p_worker_id), 160)
     AND lease_boot_id = LEFT(TRIM(p_boot_id), 160)
     AND lease_token = p_lease_token AND lease_expires_at > NOW()
   FOR UPDATE;
  IF COALESCE(owned, FALSE) = FALSE THEN
    INSERT INTO public.collection_worker_events(
      event_type, task_id, source_key, worker_id, boot_id, lease_token, idempotency_key
    ) VALUES (
      CASE WHEN p_complete THEN 'completion_rejected' ELSE 'failure_rejected' END,
      p_task_id, p_source_key, LEFT(TRIM(p_worker_id), 160), LEFT(TRIM(p_boot_id), 160),
      p_lease_token, 'finalize-rejected:' || p_lease_token::TEXT
    ) ON CONFLICT (idempotency_key) DO NOTHING;
    RETURN jsonb_build_object('applied', FALSE, 'reason', 'LEASE_FENCED');
  END IF;

  IF p_record_source_outcome THEN
    source_result := public.record_collection_source_outcome_v2(
      p_task_id, p_worker_id, p_boot_id, p_lease_token,
      p_source_key, COALESCE(p_source_success, FALSE), p_source_error_code
    );
    IF source_result->>'reason' = 'LEASE_FENCED' THEN
      RAISE EXCEPTION 'TASK_LEASE_FENCED' USING ERRCODE = '40001';
    END IF;
  END IF;

  attempt_result := public.record_collection_task_attempt_v2(
    p_task_id, p_worker_id, p_boot_id, p_lease_token, p_attempt
  );
  IF COALESCE((attempt_result->>'recorded')::BOOLEAN, FALSE) = FALSE THEN
    RAISE EXCEPTION 'TASK_ATTEMPT_NOT_RECORDED' USING ERRCODE = '40001';
  END IF;

  IF p_complete THEN
    task_result := public.complete_collection_task_v2(
      p_task_id, p_worker_id, p_boot_id, p_lease_token,
      COALESCE(p_result_summary, '{}'::jsonb) || jsonb_build_object('source_outcome', source_result)
    );
  ELSE
    task_result := public.fail_collection_task_v2(
      p_task_id, p_worker_id, p_boot_id, p_lease_token,
      p_attempt->>'error_code', p_attempt->>'error_message',
      p_backoff_seconds, p_retryable
    );
  END IF;
  IF COALESCE((task_result->>'applied')::BOOLEAN, FALSE) = FALSE THEN
    RAISE EXCEPTION 'TASK_FINAL_STATE_NOT_APPLIED' USING ERRCODE = '40001';
  END IF;
  -- A confirmed provider attempt consumes its reservation. A retry receives a
  -- new budget key; infrastructure failures before provider execution retain
  -- the old key so an ambiguous reservation response cannot charge twice.
  IF NOT p_complete
     AND p_record_source_outcome
     AND task_result->>'status' = 'retry_wait' THEN
    UPDATE public.collection_tasks
       SET budget_request_id = NULL, updated_at = NOW()
     WHERE id = p_task_id;
  END IF;

  RETURN task_result || jsonb_build_object(
    'attempt', attempt_result,
    'source_outcome', source_result
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.get_collection_worker_health()
RETURNS JSONB
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT jsonb_build_object(
    'checked_at', NOW(),
    'protocol_version', 2,
    'queued', (SELECT COUNT(*) FROM public.collection_tasks WHERE status IN ('queued', 'retry_wait')),
    'leased', (SELECT COUNT(*) FROM public.collection_tasks WHERE status = 'leased' AND lease_expires_at > NOW()),
    'dead_letter', (SELECT COUNT(*) FROM public.collection_tasks WHERE status = 'dead_letter'),
    'budget_blocked', (SELECT COUNT(*) FROM public.collection_tasks WHERE status = 'budget_blocked'),
    'open_circuits', COALESCE((SELECT jsonb_agg(source_key) FROM public.collection_source_policies WHERE circuit_state = 'open'), '[]'::jsonb),
    'half_open_circuits', COALESCE((SELECT jsonb_agg(source_key) FROM public.collection_source_policies WHERE circuit_state = 'half_open'), '[]'::jsonb),
    'sources', (SELECT COUNT(*) FROM public.collection_source_policies WHERE enabled),
    'active_workers', (
      SELECT COUNT(*) FROM public.collection_worker_instances
       WHERE status IN ('starting', 'ready', 'busy') AND last_seen_at >= NOW() - INTERVAL '2 minutes'
    ),
    'r10_ready_workers', (
      SELECT COUNT(*) FROM public.collection_worker_instances AS instance
       WHERE instance.status IN ('ready', 'busy')
         AND instance.last_seen_at >= NOW() - INTERVAL '2 minutes'
         AND instance.metadata->>'protocol_version' = '2'
         AND (
           SELECT COUNT(*) FROM public.collection_worker_heartbeat_samples AS sample
            WHERE sample.worker_id = instance.worker_id
              AND sample.observed_at >= NOW() - INTERVAL '3 minutes'
              AND sample.status IN ('ready', 'busy')
              AND sample.metadata->>'protocol_version' = '2'
         ) >= 3
    ),
    'stale_workers', (
      SELECT COUNT(*) FROM public.collection_worker_instances
       WHERE status <> 'stopped' AND last_seen_at < NOW() - INTERVAL '2 minutes'
    ),
    'last_worker_heartbeat', (SELECT MAX(last_seen_at) FROM public.collection_worker_instances),
    'tikhub_daily', COALESCE((SELECT jsonb_build_object(
      'request_count', request_count, 'estimated_cost_usd', estimated_cost_usd,
      'blocked_requests', blocked_requests
    ) FROM public.collection_usage_daily
      WHERE source_key = 'tikhub' AND usage_date = (NOW() AT TIME ZONE 'UTC')::DATE), '{}'::jsonb)
  );
$$;

CREATE OR REPLACE FUNCTION public.get_collection_worker_runtime_evidence(
  p_worker_id TEXT DEFAULT NULL,
  p_window_hours INTEGER DEFAULT 24
)
RETURNS JSONB
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  WITH bounds AS (
    SELECT NOW() AS checked_at,
           GREATEST(1, LEAST(COALESCE(p_window_hours, 24), 720))::INTEGER AS window_hours
  ),
  sample_rows AS (
    SELECT sample.observed_at, sample.status, sample.boot_id,
           LAG(sample.observed_at) OVER (ORDER BY sample.observed_at) AS previous_at
      FROM public.collection_worker_heartbeat_samples AS sample
      CROSS JOIN bounds
     WHERE (NULLIF(TRIM(p_worker_id), '') IS NULL OR sample.worker_id = LEFT(TRIM(p_worker_id), 160))
       AND sample.metadata->>'protocol_version' = '2'
       AND sample.observed_at >= bounds.checked_at - make_interval(hours => bounds.window_hours)
  ),
  sample_stats AS (
    SELECT COUNT(*) AS heartbeat_count,
           MIN(observed_at) AS first_heartbeat_at,
           MAX(observed_at) AS last_heartbeat_at,
           COALESCE(MAX(EXTRACT(EPOCH FROM (observed_at - previous_at))), 0)::NUMERIC AS max_gap_seconds,
           COUNT(DISTINCT boot_id) AS boot_count
      FROM sample_rows
  ),
  attempt_rows AS (
    SELECT attempt.status, attempt.request_id, attempt.task_id, attempt.attempt_number
      FROM public.collection_task_attempts AS attempt
      CROSS JOIN bounds
     WHERE (NULLIF(TRIM(p_worker_id), '') IS NULL OR attempt.worker_id = LEFT(TRIM(p_worker_id), 160))
       AND attempt.started_at >= bounds.checked_at - make_interval(hours => bounds.window_hours)
  ),
  task_stats AS (
    SELECT COUNT(*) AS attempt_count,
           COUNT(DISTINCT request_id) AS distinct_request_count,
           COUNT(DISTINCT task_id::TEXT || ':' || attempt_number::TEXT) AS distinct_attempt_count,
           COALESCE((
             SELECT jsonb_object_agg(grouped.status, grouped.status_count)
               FROM (
                 SELECT status, COUNT(*) AS status_count FROM attempt_rows GROUP BY status
               ) grouped
           ), '{}'::jsonb) AS status_counts
      FROM attempt_rows
  ),
  queue_stats AS (
    SELECT COALESCE(jsonb_object_agg(status, status_count), '{}'::jsonb) AS status_counts
      FROM (
        SELECT task.status, COUNT(*) AS status_count
          FROM public.collection_tasks AS task
         WHERE task.updated_at >= NOW() - make_interval(hours => GREATEST(1, LEAST(COALESCE(p_window_hours, 24), 720)))
         GROUP BY task.status
      ) grouped_tasks
  ),
  event_stats AS (
    SELECT COALESCE(jsonb_object_agg(event_type, event_count), '{}'::jsonb) AS event_counts
      FROM (
        SELECT event.event_type, COUNT(*) AS event_count
          FROM public.collection_worker_events AS event
          CROSS JOIN bounds
         WHERE (NULLIF(TRIM(p_worker_id), '') IS NULL OR event.worker_id = LEFT(TRIM(p_worker_id), 160))
           AND event.created_at >= bounds.checked_at - make_interval(hours => bounds.window_hours)
         GROUP BY event.event_type
      ) grouped_events
  )
  SELECT jsonb_build_object(
    'worker_id', NULLIF(TRIM(p_worker_id), ''),
    'protocol_version', 2,
    'window_hours', bounds.window_hours,
    'checked_at', bounds.checked_at,
    'heartbeat_count', sample_stats.heartbeat_count,
    'first_heartbeat_at', sample_stats.first_heartbeat_at,
    'last_heartbeat_at', sample_stats.last_heartbeat_at,
    'coverage_seconds', COALESCE(EXTRACT(EPOCH FROM (sample_stats.last_heartbeat_at - sample_stats.first_heartbeat_at)), 0)::NUMERIC,
    'max_gap_seconds', sample_stats.max_gap_seconds,
    'boot_count', sample_stats.boot_count,
    'attempt_count', task_stats.attempt_count,
    'distinct_request_count', task_stats.distinct_request_count,
    'duplicate_request_count', task_stats.attempt_count - task_stats.distinct_request_count,
    'distinct_attempt_count', task_stats.distinct_attempt_count,
    'duplicate_attempt_count', task_stats.attempt_count - task_stats.distinct_attempt_count,
    'attempt_status_counts', task_stats.status_counts,
    'task_status_counts', queue_stats.status_counts,
    'worker_event_counts', event_stats.event_counts
  )
    FROM bounds, sample_stats, task_stats, queue_stats, event_stats;
$$;

ALTER TABLE public.collection_source_outcomes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.collection_worker_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.collection_source_outcomes, public.collection_worker_events FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.collection_source_outcomes, public.collection_worker_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.collection_worker_events_id_seq TO service_role;

REVOKE ALL ON FUNCTION public.claim_collection_task_v2(TEXT, TEXT, INTEGER) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.renew_collection_task_lease_v2(UUID, TEXT, TEXT, UUID, INTEGER) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.record_collection_task_attempt_v2(UUID, TEXT, TEXT, UUID, JSONB) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.record_collection_source_outcome_v2(UUID, TEXT, TEXT, UUID, TEXT, BOOLEAN, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.complete_collection_task_v2(UUID, TEXT, TEXT, UUID, JSONB) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.fail_collection_task_v2(UUID, TEXT, TEXT, UUID, TEXT, TEXT, INTEGER, BOOLEAN) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.finalize_collection_task_v2(UUID, TEXT, TEXT, UUID, JSONB, TEXT, BOOLEAN, BOOLEAN, TEXT, JSONB, BOOLEAN, INTEGER, BOOLEAN) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.get_collection_worker_runtime_evidence(TEXT, INTEGER) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.claim_collection_task_v2(TEXT, TEXT, INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION public.renew_collection_task_lease_v2(UUID, TEXT, TEXT, UUID, INTEGER) TO service_role;
GRANT EXECUTE ON FUNCTION public.record_collection_task_attempt_v2(UUID, TEXT, TEXT, UUID, JSONB) TO service_role;
GRANT EXECUTE ON FUNCTION public.record_collection_source_outcome_v2(UUID, TEXT, TEXT, UUID, TEXT, BOOLEAN, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.complete_collection_task_v2(UUID, TEXT, TEXT, UUID, JSONB) TO service_role;
GRANT EXECUTE ON FUNCTION public.fail_collection_task_v2(UUID, TEXT, TEXT, UUID, TEXT, TEXT, INTEGER, BOOLEAN) TO service_role;
GRANT EXECUTE ON FUNCTION public.finalize_collection_task_v2(UUID, TEXT, TEXT, UUID, JSONB, TEXT, BOOLEAN, BOOLEAN, TEXT, JSONB, BOOLEAN, INTEGER, BOOLEAN) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_collection_worker_runtime_evidence(TEXT, INTEGER) TO service_role;

COMMENT ON COLUMN public.collection_tasks.lease_token IS 'Per-claim fencing token; stale Worker writes cannot mutate a newer lease.';
COMMENT ON COLUMN public.collection_tasks.budget_request_id IS 'Stable execution budget key reused across ambiguous infrastructure retries and rotated after a confirmed provider attempt.';
COMMENT ON TABLE public.collection_source_outcomes IS 'One idempotent circuit outcome per fenced task lease.';
COMMENT ON TABLE public.collection_worker_events IS 'Service-only audit trail for claims, fencing decisions, circuit transitions and terminal outcomes.';
COMMENT ON FUNCTION public.claim_collection_task_v2(TEXT, TEXT, INTEGER) IS 'Atomically claims one task with a fencing token and permits only one half-open circuit probe.';

COMMIT;
